apiVersion: v1
kind: Service
metadata:
  name: legal-app-frontend-service
spec:
  selector:
    app: legal-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
