apiVersion: v1
kind: Service
metadata:
  name: legal-app-service
spec:
  selector:
    app: legal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer # Change to NodePort or ClusterIP as needed
